# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/testpc/fpga_asist_dev/validation_test/si5351_ad9238_hdmi_project/fpga/constraints/pins.xdc

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
